name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Exec unit tests
        run: |
          sh scripts/unit-test.sh

      - name: Build
        run: |
          cargo build --release

      - name: Exec integration tests
        run: |
          sh scripts/integration-test.sh

      - name: Release for each OS
        run: |
          sh scripts/release.sh
