name: unit-test

on:
  push:
    branches:
      - dev

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Exec unit tests
        run: |
          sh scripts/unit-test.sh
